# Generated by Django 2.1.3 on 2018-12-11 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apptags', '0005_auto_20181211_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='popular',
            name='hashtags',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apptags.Hashtags'),
        ),
    ]
