# Generated by Django 2.1.3 on 2018-12-11 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apptags', '0008_auto_20181211_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='popular',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='popular',
            name='hashtags',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apptags.Hashtags'),
        ),
    ]
