# Generated by Django 2.1.3 on 2018-12-11 17:51

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apptags', '0009_auto_20181211_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='popular',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='popular',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='popular',
            name='img',
            field=models.ImageField(default=1, upload_to='img-tags'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='popular',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='popular',
            name='tags',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='popular',
            name='hashtags',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apptags.Hashtags'),
        ),
    ]
