# Generated by Django 2.1.3 on 2018-12-17 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apptags', '0013_auto_20181217_0143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alltags',
            name='user',
        ),
        migrations.RemoveField(
            model_name='popular',
            name='hashtags',
        ),
        migrations.DeleteModel(
            name='Alltags',
        ),
    ]
