# Generated by Django 2.1.3 on 2018-12-17 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apptags', '0014_auto_20181217_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='animals',
            name='hashtag',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='apptags.Hashtags'),
            preserve_default=False,
        ),
    ]
