# Generated by Django 2.1.3 on 2018-12-17 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apptags', '0018_auto_20181218_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animals',
            name='hashtag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apptags.Hashtags'),
        ),
        migrations.AlterField(
            model_name='art_photography',
            name='hashtag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apptags.Hashtags'),
        ),
        migrations.AlterField(
            model_name='celebrities',
            name='hashtag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apptags.Hashtags'),
        ),
        migrations.AlterField(
            model_name='electronics',
            name='hashtag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apptags.Hashtags'),
        ),
        migrations.AlterField(
            model_name='entertainment',
            name='hashtag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apptags.Hashtags'),
        ),
        migrations.AlterField(
            model_name='family',
            name='hashtag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apptags.Hashtags'),
        ),
        migrations.AlterField(
            model_name='fashion',
            name='hashtag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apptags.Hashtags'),
        ),
        migrations.AlterField(
            model_name='follow_shoutout_like_comment',
            name='hashtag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apptags.Hashtags'),
        ),
        migrations.AlterField(
            model_name='food',
            name='hashtag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apptags.Hashtags'),
        ),
        migrations.AlterField(
            model_name='holidays_celebrations',
            name='hashtag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apptags.Hashtags'),
        ),
        migrations.AlterField(
            model_name='nature',
            name='hashtag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apptags.Hashtags'),
        ),
        migrations.AlterField(
            model_name='other',
            name='hashtag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apptags.Hashtags'),
        ),
        migrations.AlterField(
            model_name='popular',
            name='hashtag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apptags.Hashtags'),
        ),
        migrations.AlterField(
            model_name='social_people',
            name='hashtag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apptags.Hashtags'),
        ),
        migrations.AlterField(
            model_name='textart',
            name='hashtag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apptags.Hashtags'),
        ),
        migrations.AlterField(
            model_name='travel_active_sports',
            name='hashtag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apptags.Hashtags'),
        ),
        migrations.AlterField(
            model_name='urban',
            name='hashtag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apptags.Hashtags'),
        ),
        migrations.AlterField(
            model_name='weather_seasons',
            name='hashtag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apptags.Hashtags'),
        ),
    ]
